### ISSUE TITLE
Submission - Jaimeloeuf

### ISSUE THREAD

**Issue by Jaimeloeuf** [nushackers/openhack-submissions#14]
## Submission Details

**Type of Submission:**

- [ ] 3 Pull requests
- [x] Self-initiated open-source project

**Link to open-source project:**
https://github.com/Enkel-Digital/relativity

**Additional information (optional):**
Hello, this is kinda late, but I literally just saw the post about this hack 10 mins ago.... so here goes..

This project is a vs code cursor navigation extension, inspired by vim's ability to move the cursor arounds using relative line and character numbers!

On vs code right now, when u use goto, u must specify absolute numbers, and when u are using relative line numbers, and u press the goto shortcut, they turn all the line numbers back into absolute numbers, which is kinda missing the point of using relative numbers in the first place....

So the solution to this is:
1. Use vim instead.... (hard for most users especially beginners)
2. Use the vim keymap for vs code... (well, same as point 1 it is hard)
3. Wait for vs code to implement this feature (well they tried, but it took too long like years and still no progress)
4. Build an extension myself!!

So basically I started with building a extension that will allow me to jump using relative line numbers using a shortcut. After this is done, I realise that I used to hold down shift and move use up/down ALOT to select a chunk of text, which is kinda dumb and make me press the up/down key too many times...
So I added a new feature on top of the relative line number jumping, to select a chunk of text from ur current cursor position to the specified jump destination!

(Copied from README)
Visual Studio Code extension "relativity" allows you to jump to lines relative to the current line and select them if you wish.

### Lastly
There is some small issue right now with keyboard shortcuts on macs, but it is hard for me to test them as I do not own a mac.... so if anyone is kind enough to work with me on this, it would be great!

**Comment by chaitanyabaranwal** [comment]
Hey @Jaimeloeuf, so sorry for the super late reply! The project looks great to me. Thanks for sharing your work and your OpenHack submission is now accepted!

Please visit https://openhack.nushackers.org/congrats and fill up the form so that we can capture your details for the prizes.

We hope you had fun working on the challenge and we hope you will continue making open-source contributions, even outside of the event! 😃

**Comment by Jaimeloeuf** [comment]
@chaitanyabaranwal thanks, had fun making it too and use it daily on my own setup!
