### ISSUE TITLE
Submission - J0

### ISSUE THREAD

**Issue by J0** [nushackers/openhack-submissions#4]
## Submission Details

**Type of Submission:**

- [ ] 3 Pull requests
- [x] Self-initiated open-source project

**Link to open-source project:**
[pyfluminus gui](https://github.com/J0/pyfluminus_gui)
<image coming once virtualenv is done>

**Additional information (optional):**
- Builds on @raynoldng's gui and @indocomsoft's original luminus api

**Comment by J0** [comment]
As an NUS Hackers coreteam member, I am also disqualifying myself. Hopefully this project gives people ideas :D

**Comment by chrisgzf** [comment]
Cool project! But it wouldn't have qualified for prizes anyway because it's not created during the challenge period. 😟Can I add this to the list of repos that the OpenHack participants can contribute to?

**Comment by J0** [comment]
yep! I mean, for starters I'm not a student anymore too(fingers crossed). Yeah, sure go ahead and add it. I need to update the README with instructions on how to get set up. You can add it first but it'll only be ready sunday morning-ish

Thanks for managing this!

**Comment by J0** [comment]
Closing this because Open Hack has ended (I think)
